import { randomBytes } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { createDesktopService } from './service.js';
const root=resolve(process.env.AGENT_DATA_ROOT??'.data');
const tokenPath=join(root,'api-token');
const cliproxyKeyPath=join(root,'cliproxy-api-key');
const token=process.env.AGENT_API_TOKEN??((await readFile(tokenPath,'utf8').then(v=>v.trim()).catch(()=>''))||randomBytes(32).toString('hex'));
let localKey=process.env.AGENT_CLIPROXY_KEY??((await readFile(cliproxyKeyPath,'utf8').then(v=>v.trim()).catch(()=>''))||randomBytes(32).toString('hex'));
const values:Record<string,string>={openai:process.env.OPENAI_API_KEY??'',custom:process.env.CUSTOM_API_KEY??''};
const service=await createDesktopService({root,token,localKey,proxyPort:process.env.AGENT_PROXY_PORT?Number(process.env.AGENT_PROXY_PORT):undefined,binary:process.env.CLIPROXY_BINARY?resolve(process.env.CLIPROXY_BINARY):resolve('sidecars',`${process.platform}-${process.arch}`,process.platform==='win32'?'cliproxyapi.exe':'cliproxyapi'),headless:process.env.AGENT_HEADLESS==='1',uiRoot:resolve('dist/console'),secrets:{get:async name=>name==='cliproxy'?localKey:values[name]??'',set:async(name,value)=>{if(name==='cliproxy'){localKey=value;await writeFile(cliproxyKeyPath,value,{mode:0o600});return;}values[name]=value;}}});
await writeFile(tokenPath,token,{mode:0o600});
await writeFile(cliproxyKeyPath,localKey,{mode:0o600});
const address=await service.app.listen({host:'127.0.0.1',port:Number(process.env.AGENT_PORT??9527)});
console.log(`token-flowb API: ${address}\nWorkspace token: ${tokenPath}\nLocal Agent key: ${cliproxyKeyPath}\nUse npm start for the authenticated desktop UI.`);
for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>{void service.app.close().then(()=>process.exit(0));});
