import { QuotaRing } from './QuotaRing';
import { modelLabel } from './model-label';
import { copyText } from './clipboard';
import { sourceOptions } from './source-options';
import { useEffect,useState,useRef,useId } from 'react';
import type { LocalAgentSnapshot } from '../../../packages/core/src/cliproxy';
import type { AgentConnections } from '../../../packages/core/src/agent-connections';
import type { MaintenanceReadiness } from '../../../packages/core/src/gateway-maintenance';
import { Icon } from './Icons';
type TargetStatus=Awaited<ReturnType<AgentConnections['status']>>[number];
async function request<T>(path:string,body?:unknown,method='POST'):Promise<T>{const r=await fetch(path,{method:body===undefined?'GET':method,...(body===undefined?{}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw new Error(data.error?.message??data.error??data.message??'操作失败');return data;}
export function SourceChoice({local,source,model,onChange}:{local:LocalAgentSnapshot;source:string;model:string;onChange:(source:string,model:string)=>void}) {
 const titleId=useId();
 const [opened,setOpened]=useState<string>();const dialog=useRef<HTMLDialogElement>(null);const trigger=useRef<HTMLButtonElement|null>(null);
 const accounts=sourceOptions(local);const account=accounts.find(a=>a.id===opened);
 const close=()=>{dialog.current?.close();setOpened(undefined);trigger.current?.focus();};
 useEffect(()=>{if(opened&&!account)close();},[opened,!!account]);
 return <><div className="a2aSources">{accounts.map(account=><button key={account.id} className={`a2aSource ${source===account.id?'lit':''}`} disabled={local.state!=='running'} aria-pressed={source===account.id} aria-haspopup="dialog" onClick={e=>{trigger.current=e.currentTarget;setOpened(account.id);dialog.current?.showModal();}}><QuotaRing compact remaining={account.remaining} label="账号额度"/><strong>{local.providers.find(p=>p.id===account.provider)?.label??account.provider}</strong><span>{account.label}</span><small>{account.remaining===null?'额度暂未返回':`剩余 ${Math.round(account.remaining)}%`}</small>{source===account.id&&model&&<b className="selectedSourceModel" title={model}>{modelLabel(local.models,model)}</b>}</button>)}</div>{!accounts.length&&<p className="hint">{local.state==='starting'?'正在读取本地授权…':local.accounts.some(a=>!a.disabled&&!a.unavailable)?'授权已读取，正在自动同步模型，无需重新登录。':local.accountError||'暂无可用授权，登录一个 Agent 就能开始。'}</p>}
 <dialog className="modelPicker" ref={dialog} aria-labelledby={titleId} onCancel={()=>{setOpened(undefined);trigger.current?.focus();}} onClick={e=>{if(e.target===dialog.current)close();}}><div className="sectionTitle"><div><h2 id={titleId}>用哪个模型？</h2><p className="hint">{account?.label}</p></div><button className="iconButton" aria-label="关闭模型选择" onClick={close}><Icon name="close"/></button></div><div className="modelPickerList">{account?.models.map(id=><button key={id} title={`调用 ID：${id}`} onClick={()=>{onChange(account.id,id);close();}}><span>{modelLabel(local.models,id)}</span><Icon name="arrow" size={16}/></button>)}</div></dialog></>;
}
export function A2APane({local,onManual,onAccounts,onMaintenance}:{local:LocalAgentSnapshot;onManual:()=>void;onAccounts:()=>void;onMaintenance:()=>void}){
 const [targets,setTargets]=useState<TargetStatus[]>([]);const [source,setSource]=useState('');const [model,setModel]=useState('');const [target,setTarget]=useState<TargetStatus['id']|'qoder'>('claude');const [limit,setLimit]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const [reviewNotice,setReviewNotice]=useState('');
 const [qoder,setQoder]=useState<{apiKey:string;model:string;sourceId:string}>();
 const [reviewState,setReviewState]=useState<{status:string;readiness?:MaintenanceReadiness;messages:{role:string;text:string}[];liveText?:string}>({status:'idle',messages:[]});
 const [repair,setRepair]=useState<{sourceId:string;model:string}>();const [choosingRepair,setChoosingRepair]=useState(false);const [discovery,setDiscovery]=useState('loading');
 const refresh=async()=>{const [data,maintenance]=await Promise.all([request<{targets:TargetStatus[];discovery:{state:string}}>('/api/a2a'),request<{selection?:{sourceId:string;model:string};status:string;messages:{role:string;text:string}[]}>('/api/maintenance')]);setTargets(data.targets);setDiscovery(data.discovery.state);setRepair(maintenance.selection);setReviewState(maintenance);};
 useEffect(()=>{void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(()=>{}),4000);return()=>clearInterval(timer);},[]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);await refresh().catch(()=>{});}};
 const selected=targets.find(t=>t.id===target);const available=sourceOptions(local);const valid=available.some(a=>a.id===source&&a.models.includes(model));
 const connected=target!=='qoder'&&!!selected?.connection;const connectedHint='🤔 想换模型的话，请先还原接口。';
 const reason=connected?connectedHint:local.state==='failed'?'网关启动失败，请在网关设置中重试。':local.state==='stopped'?'网关已停止，请先在网关设置中启动。':local.state!=='running'?'网关正在准备，稍等一下。':!valid?'先点亮一个授权，并选择模型。':target==='qoder'?'':!selected?'正在检查本地 Agent…':selected.error?selected.error:'';
 const connect=()=>act(async()=>{if(reason){setNotice(reason);return;}if(target==='qoder'){const created=await request<{apiKey:string}>('/api/gateway-keys',{name:'A2A · Qoder',sourceId:source,models:[model],agents:['openai'],tokenLimit:limit===''?null:Number(limit)});setQoder({apiKey:created.apiKey,model,sourceId:source});return;}const latest=(await request<{targets:TargetStatus[]}>('/api/a2a')).targets.find(t=>t.id===target);const allowRunning=!!latest?.pids.length;if(allowRunning&&!window.confirm(`检测到 ${selected!.name} 还在运行，是否确认接入设置？\n会先备份原配置，再写入新设置。完成后请重启 ${selected!.name}。`))return;const result=await request<{review:{status:string;message:string}}>('/api/a2a/connect',{allowRunning,target,sourceId:source,model,revision:selected!.revision,tokenLimit:limit===''?null:Number(limit)});setReviewNotice(result.review.status==='running'?'':result.review.message);setNotice(target==='workbuddy'?`已添加 ${model}，在 WorkBuddy 新建任务的输入框下方打开模型菜单，选择 token-flowb · ${model}。若没出现，请重启 WorkBuddy。原账号登录和内置模型已保留。`:`已接入 ${selected!.name}，请重启后使用新设置。原配置已自动备份。`);});
 return <div className="a2aPage"><div className="gatewayHero"><div><h1>让你的模型，流向每个 Agent。</h1><p>{discovery==='loading'?'正在准备网关，读取本地已有授权…':available.length?`已读取 ${available.length} 份可用授权，选一个模型开始。`:local.accounts.some(a=>!a.disabled&&!a.unavailable)?'已找到本地授权，正在同步可用模型…':'还没有可用授权，登录一个 Agent 开始。'}</p></div><button className="textButton" onClick={onAccounts}>登录其他 Agent <Icon name="plus" size={15}/></button></div>
 <section className="repairWelcome"><div><span className="repairAvatar"><Icon name="sliders" size={20}/></span><div><h2>{!repair?'先指定一位维修师傅':reviewState.readiness?.status==='ready'?'你的网关维修师傅已就位':reviewState.readiness?.status==='checking'?'正在检测维修模型…':'维修模型需要检测'}</h2><p>{repair?`${modelLabel(local.models,repair.model)} · ${reviewState.readiness?.message??'尚未检测连接'}`:'接入遇到问题时，让我来帮你。'}</p></div></div><div className="buttons">{repair&&<><button disabled={busy||reviewState.status==='running'||reviewState.readiness?.status==='checking'} onClick={()=>void act(async()=>{setReviewState(await request('/api/maintenance/check',{}));})}>{reviewState.readiness?.status==='ready'?'重新检测':'检测连接'}</button><button onClick={onMaintenance}>找师傅帮忙</button></>}<button className={repair?'textButton':''} onClick={()=>setChoosingRepair(v=>!v)}>{choosingRepair?'收起':repair?'更换师傅':'指定维修师傅'}</button></div></section>
 {reviewNotice&&<p className="hint" role="status">{reviewNotice}</p>}
 {repair&&reviewState.status!=='idle'&&<div className="reviewResult" role="status"><span>{reviewState.status==='running'?'维修师傅正在检查…':reviewState.status==='failed'?'检查未完成，接入配置仍保留':reviewState.messages.filter(m=>m.role==='assistant').at(-1)?.text.slice(0,180)||'检查已完成'}</span><button onClick={onMaintenance}>查看检查 · 继续问</button></div>}
 {choosingRepair&&<section className="repairChooser"><p className="hint">选择授权，再点选一个模型作为维修师傅。</p><SourceChoice local={local} source={repair?.sourceId??''} model={repair?.model??''} onChange={(sourceId,model)=>void act(async()=>{setReviewState(await request('/api/maintenance',{sourceId,model},'PUT'));setRepair({sourceId,model});setChoosingRepair(false);setNotice('正在通过 Responses API 检测维修模型，通过后师傅就位。');})}/></section>}
 {error&&<p className="banner error" role="alert">{error}</p>}{notice&&<p className="banner notice" role="status">{notice}</p>}
 <div className="a2aFlow"><section><div className="sectionTitle"><h2>点亮源 Agent</h2><span title="多个额度窗口取最低剩余比例，未知额度排在最后">按剩余额度排序</span></div><SourceChoice local={local} source={source} model={model} onChange={(s,m)=>{setSource(s);setModel(m);setNotice('');}}/></section><div className="a2aArrow"><Icon name="arrow" size={24}/></div><section><div className="sectionTitle"><h2>想在哪个 Agent 里用？</h2></div><div className="a2aTargets">{targets.map(t=><button key={t.id} aria-pressed={target===t.id} className={target===t.id?'lit':''} onClick={()=>{setTarget(t.id);setNotice('');}}><Icon name="plug"/><strong>{t.name}</strong><small>{t.connection?'已接入':t.pids.length?'正在运行':'可接入'}</small></button>)}<button aria-pressed={target==='qoder'} className={target==='qoder'?'lit':''} onClick={()=>{setTarget('qoder');setNotice('');}}><Icon name="plug"/><strong>Qoder IDE</strong><small>需在 Qoder 确认添加</small></button></div><p className="hint">接入只更改模型接口，本地授权池仍可供其他 Agent 使用。</p>
 <div className="connectAction"><button className="primary" title={connected?connectedHint:undefined} disabled={busy||(!connected&&(!valid||local.state!=='running'||(target!=='qoder'&&(!selected||!!selected.error))||(target==='qoder'&&qoder?.model===model&&qoder.sourceId===source)))} onClick={()=>connected?setNotice(connectedHint):void connect()}>{busy?'正在接入…':target==='qoder'?(qoder?.model===model&&qoder.sourceId===source?'等待在 Qoder 添加':'接入 Qoder'):selected?.connection?'已接入':`接入 ${selected?.name??'Agent'}`}</button><p className="hint" role="status">{reason||(target==='qoder'?'Qoder 需在设置中确认添加一次，暂不支持自动写入。原账号和内置模型保留。':'原配置会自动备份，随时可以还原。')}</p></div>
 {target==='qoder'&&qoder&&qoder.model===model&&qoder.sourceId===source&&<section className="qoderGuide" aria-label="Qoder 接入参数"><h3>在 Qoder 添加这个模型</h3><p className="hint">Settings → Models → Add → OpenAI Compatible → Responses</p>{[['Base URL',`${location.origin}/v1`],['Model ID',qoder.model],['API Key',qoder.apiKey]].map(([label,value])=><label key={label}>{label}<div className="inputAction"><input aria-label={label} readOnly type={label==='API Key'?'password':'text'} value={value} onFocus={e=>e.target.select()}/><button onClick={()=>void copyText(value).then(()=>setNotice(`${label} 已复制`)).catch(()=>setError('复制失败，请选中内容手动复制。'))}>复制 {label}</button></div></label>)}<p className="hint">点击 Qoder 的“验证并添加”，再在对话中选用该模型。Key 完整值仅在本页保留，请先复制；可在 API Keys 中管理。</p><details><summary>使用 Qoder CLI？</summary><p className="hint">在 /model → Custom 向导中添加，供应商与地址字段以当前版本和账号目录为准。没有自定义地址选项时，使用 Qoder IDE；无需改动本机登录。</p></details><a href="https://docs.qoder.com/qoder/custom-models" target="_blank" rel="noreferrer">Qoder 官方接入说明 ↗</a></section>}
 <details className="connectionDetails"><summary>接入设置与详情</summary><label>Token 额度<input type="number" min="0" max="1000000000000" step="1" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="不限额"/></label><p className="hint">按实际输入与输出累计结算。最后一次请求可能超过额度。</p>{target!=='qoder'&&selected&&<p className="hint">配置文件：<code>{selected.path}</code>{selected.pids.length?`运行进程：${selected.pids.join(', ')}`:''}</p>}<button onClick={onManual}>其他 Agent / 手动接入</button></details></section></div>
 {targets.some(t=>t.connection)&&<section className="a2aConnections"><div className="sectionTitle"><h2>正在使用</h2><button disabled={busy} onClick={()=>void act(refresh)}>刷新</button></div>{targets.filter(t=>t.connection).map(t=><div className="a2aConnection" key={t.id}><div><strong>{t.name}</strong><span title={t.connection!.model}>{modelLabel(local.models,t.connection!.model)}</span><small>{t.drift?'配置有新改动，找维修师傅检查一下':t.connection!.state==='prepared'?'接入未完成，可以找师傅检查':'原接口已备份，随时可还原'}</small>{!!t.pids.length&&<small>还原前请先退出 {t.name}。</small>}</div><button disabled={busy||reviewState.status==='running'} onClick={()=>{if(!repair){setChoosingRepair(true);setNotice('先指定一位维修师傅，就能检查这次接入。');return;}void act(async()=>{await request('/api/maintenance/run',{prompt:`请复查 ${t.name} 接入（记录 ${t.connection!.id}），检查配置、模型权限、备份与进程，并说明是否还需重启或选模型。`,allowRestore:false});onMaintenance();});}}>请师傅复查</button><button disabled={busy||!!t.pids.length} onClick={()=>void act(async()=>{await request('/api/a2a/restore',{id:t.connection!.id});setNotice('原接口已还原。');})}>还原原接口</button></div>)}</section>}</div>;
}
export function MaintenancePane({local}:{local:LocalAgentSnapshot}){
 const [source,setSource]=useState('');const [model,setModel]=useState('');const [prompt,setPrompt]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [allowRestore,setAllowRestore]=useState(false);
 const [state,setState]=useState<{selection?:{sourceId:string;model:string};status:string;readiness?:MaintenanceReadiness;messages:{role:string;text:string}[];liveText?:string}>({status:'idle',messages:[]});
 useEffect(()=>{let first=true;const refresh=async()=>{const next=await request<typeof state>('/api/maintenance');setState(next);if(first){setSource(next.selection?.sourceId??'');setModel(next.selection?.model??'');first=false;}};void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(()=>{}),1500);return()=>clearInterval(timer);},[]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}};
 return <div className="maintenancePane"><div className="gatewayHero"><div><span className="eyebrow">GATEWAY CARE</span><h1>接入对不对，问问维修师傅。</h1><p>维修模型检测通过后，接入会自动检查。可以继续描述问题；失败后会重新检查，避免反复卡住。</p></div><div className="buttons"><button disabled={busy||state.status==='running'||state.readiness?.status==='checking'} onClick={()=>void act(async()=>{setState(await request('/api/maintenance/reset',{}));})}>新开对话</button>{state.status==='running'&&<button onClick={()=>void act(async()=>{setState(await request('/api/maintenance/stop',{}));})}>停止检查</button>}</div></div><details open={!state.selection}><summary>{state.selection?`维修模型 · ${modelLabel(local.models,state.selection.model)}`:'选择网关维修模型'}</summary><SourceChoice local={local} source={source} model={model} onChange={(s,m)=>{setSource(s);setModel(m);}}/><button className="primary" disabled={!source||!model||busy||state.status==='running'||state.readiness?.status==='checking'} onClick={()=>void act(async()=>{setState(await request('/api/maintenance',{sourceId:source,model},'PUT'));})}>设为维修模型</button></details>{state.selection&&<div className="reviewResult" role="status"><span>{state.readiness?.message??'尚未检测维修模型连接。'}{state.readiness?.checkedAt&&`（${new Date(state.readiness.checkedAt).toLocaleTimeString()}）`}</span><button disabled={busy||state.status==='running'||state.readiness?.status==='checking'} onClick={()=>void act(async()=>{setState(await request('/api/maintenance/check',{}));})}>重新检测</button></div>}{error&&<p role="alert" className="banner error">{error}</p>}<div className="maintenanceMessages" aria-live="polite">{!state.messages.length?<div className="empty"><Icon name="sliders" size={28}/><h2>从一次接入检查开始</h2><p>模型可以检查网关、刷新授权状态，并在你要求时还原备份。</p></div>:state.messages.map((m,i)=><div key={i} className={`maintenanceMessage ${m.role}`}><strong>{m.role==='user'?'你':m.role==='tool'?'工具执行':m.role==='error'?'执行失败':'维修助手'}</strong>{m.role==='tool'?<details><summary>查看执行结果</summary><pre>{m.text}</pre></details>:<p>{m.text}</p>}</div>)}{state.status==='running'&&<p role="status">{state.liveText||'维修师傅正在检查…'}</p>}</div><form onSubmit={e=>{e.preventDefault();void act(async()=>{setState(await request('/api/maintenance/run',{prompt,allowRestore}));setPrompt('');setAllowRestore(false);});}}><label>维修任务<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="例如：刚才接入正确吗？为什么 WorkBuddy 还在用原模型？" maxLength={8000}/></label><label className="scopeCheck"><input type="checkbox" checked={allowRestore} onChange={e=>setAllowRestore(e.target.checked)}/>允许本次维修修复或还原接入配置（仍检查进程和配置冲突）</label><div className="buttons"><button type="button" onClick={()=>setPrompt('检查当前网关和所有 Agent 接入状态，说明配置、进程或模型授权存在的问题。')}>检查接入</button><button className="primary" disabled={!state.selection||!prompt.trim()||busy||state.status==='running'||state.readiness?.status==='checking'||local.state!=='running'}>开始维修</button></div><p className="hint">执行会消耗所选模型额度。不会强制关闭进程或覆盖外部修改；网关完全离线时仍可在 A2A 页面使用本地还原。</p></form></div>;
}
