import { A2APane, MaintenancePane } from './A2APane';
import { copyText } from './clipboard';
import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { RunDetail, RunRecord } from '@cua-sample/contracts';
import { ScreenshotPane } from './ScreenshotPane';
import './style.css';
import { Icon, type IconName } from './Icons';
import { GatewayHome } from './GatewayHome';
import { AgentConnections } from './AgentConnections';
import { GatewayKeysPane } from './GatewayKeysPane';
import { LocalAgentPane } from './LocalAgentPane';
import type { LocalAgentSnapshot } from '../../../packages/core/src/cliproxy';

type Provider={engine?:'legacy'|'pi';kind:'cliproxy'|'openai'|'custom';baseURL:string;model:string;historyMode:'stateless'|'previous_response_id';reasoning:'off'|'low'|'medium'|'high'};
type Control={state:string;pending?:{id:string;kind:'human';message:string}};
type Local=LocalAgentSnapshot;
type Probe={responses:boolean;functionCall:boolean;functionOutput:boolean;previousResponseId:boolean;imageInput:boolean;reasoning:boolean;errors:Record<string,string>};
async function api<T>(path:string,body?:unknown,method?:string):Promise<T>{
  const response=await fetch(path,{method:method??(body===undefined?'GET':'POST'),headers:body===undefined?undefined:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await response.json();if(!response.ok)throw new Error(data.error??data.message??`HTTP ${response.status}`);return data;
}
const stateNames:Record<string,string>={idle:'空闲',agent_control:'Agent 正在操作',pausing:'等待当前操作结束',human_control:'人工接管',resync:'同步页面状态',running:'运行中',completed:'已完成',failed:'失败',cancelled:'已停止',stopped:'已停止',starting:'启动中'};
function App(){
  const [modelView,setModelView]=useState<'accounts'|'connection'|'gateway'|'keys'>('accounts');
  const [credentialWarnings,setCredentialWarnings]=useState<string[]>([]);
  const [preferredModel,setPreferredModel]=useState('');
  const [previewOpen,setPreviewOpen]=useState(false);
  const [optionsOpen,setOptionsOpen]=useState(false);
  const [historyQuery,setHistoryQuery]=useState('');
  const [historyStatus,setHistoryStatus]=useState('all');
  const [tab,setTab]=useState('a2a');
  useEffect(()=>{document.querySelector('main')?.scrollTo(0,0);},[tab]);
  const [returnAfterLogin,setReturnAfterLogin]=useState<string|null>(null);
  const [taskMode,setTaskMode]=useState<'maintenance'|'browser'>('maintenance'); const [error,setError]=useState('');const [busy,setBusy]=useState('');
  const [provider,setProvider]=useState<Provider>({kind:'cliproxy',baseURL:'http://127.0.0.1:8317/v1',model:'',historyMode:'stateless',reasoning:'off'});
  const [apiKey,setApiKey]=useState('');const [hasKey,setHasKey]=useState(false); const [probe,setProbe]=useState<Probe>();const [models,setModels]=useState<{id:string}[]>([]);
  const [control,setControl]=useState<Control>({state:'idle'});const [local,setLocal]=useState<Local>({state:'stopped',loginState:'idle',port:8317,logs:[],accounts:[],models:[],accountError:undefined,lastError:undefined,quotas:{},quotaBusy:false,providers:[],login:undefined});
  const [browser,setBrowser]=useState<{running:boolean;source?:'dedicated'|'extension';tabs:{index:number;url:string;title:string}[]}>({running:false,tabs:[]});
  const [desktop,setDesktop]=useState<{enabled:boolean;supported:boolean;platform:string;permissions?:{screenRecording:boolean|'unknown';accessibility:boolean|'unknown'}}>({enabled:false,supported:false,platform:''});
  const [run,setRun]=useState<RunDetail|null>(null);const [active,setActive]=useState<RunDetail|null>(null);const [history,setHistory]=useState<RunRecord[]>([]);
  const [connection,setConnection]=useState('');
  const [prompt,setPrompt]=useState('');const [turns,setTurns]=useState(24);const [frame,setFrame]=useState<number|null>(null);const [notice,setNotice]=useState('');
  async function refresh(){
    const results=await Promise.allSettled([
      api<Local>('/api/local-agent').then(setLocal),
      api<Control>('/api/control').then(setControl),
      api<typeof browser>('/api/browser').then(setBrowser),
      api<RunDetail|null>('/api/runs/active').then(a=>{setActive(a);if(a)setRun(current=>!current||current.run.id===a.run.id?a:current);}),
      api<RunRecord[]>('/api/history').then(setHistory),
      api<typeof desktop>('/api/desktop').then(setDesktop),
    ]);
    const failed=results.find(result=>result.status==='rejected');if(failed?.status==='rejected')throw failed.reason;
  }
  const act=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}};
  useEffect(()=>{void api<{provider:Provider;hasKey:boolean;probe?:Probe;credentialWarnings?:string[]}>('/api/settings').then(s=>{setProvider(s.provider);setHasKey(s.hasKey);setProbe(s.probe);setCredentialWarnings(s.credentialWarnings??[]);}).catch(e=>setError(e.message));void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(()=>{}),1500);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(returnAfterLogin!==null&&local.login?.status==='completed'&&local.login.id!==returnAfterLogin){setTab('a2a');setReturnAfterLogin(null);}},[local.login?.id,local.login?.status,returnAfterLogin]);
  useEffect(()=>{if(!active)return;const stream=new EventSource(active.eventStreamUrl);stream.onmessage=event=>{const data=JSON.parse(event.data);if(['run_completed','run_failed','run_cancelled'].includes(data.type)){setActive(null);setControl({state:'idle'});}void api<RunDetail>(`/api/runs/${active.run.id}`).then(setRun).catch(()=>{});};return()=>stream.close();},[active?.run.id]);
  const shots=run?.browser?.screenshots??[];const index=frame===null?shots.length-1:Math.min(frame,shots.length-1);const shot=shots[index]??null;
  const save=async()=>{await api('/api/settings',{provider,...(apiKey?{apiKey}:{})},'PUT');setApiKey('');setHasKey(provider.kind==='cliproxy'||!!apiKey||hasKey);setProbe(undefined);};
  const command=(action:string)=>act(action,async()=>{setLocal(await api(`/api/local-agent/${action}`,{}));});
  const desktopPlatform = (window as Window & {desktop?:{platform:string}}).desktop?.platform;
  const reviewing = !!run || previewOpen;
  const visibleHistory=history.filter(item=>(historyStatus==='all'||item.status===historyStatus)&&`${item.prompt} ${item.model}`.toLocaleLowerCase().includes(historyQuery.trim().toLocaleLowerCase()));
  const openHistory=(id:string)=>act('读取历史',async()=>{setRun(await api(`/api/runs/${id}`));setFrame(null);setTab('task');});
  const newTask = () => {setRun(null);setPrompt('');setFrame(null);setPreviewOpen(false);setOptionsOpen(false);setTab('task');};
  return <div className={`app ${desktopPlatform==='darwin'?'nativeMac':''}`}>
    <aside className="sidebar">
      <div className="brand"><img className="mark" src="/logo.svg" alt="" width="38" height="38"/><div>token-flowb<small>你的模型，流向每个 Agent</small></div></div>
      <button className="newTask" onClick={()=>{setTab('models');setModelView('accounts');}}><Icon name="plus"/>连接厂商账号</button>
      <span className="navLabel">模型网关</span>
      <nav aria-label="主导航">{[['a2a','plug','A2A 接入'],['gateway','workspace','API 总览'],['models','model','模型中心'],['agents','plug','Agent 接入'],['keys','shield','API Keys']].map(([id,icon,name])=><button key={id} className={tab===id?'selected':''} aria-current={tab===id?'page':undefined} aria-label={name} onClick={()=>{setTab(id);if(id==='models')setModelView('accounts');}}><Icon name={icon as IconName}/>{name}</button>)}</nav>
      <span className="navLabel secondaryLabel">辅助工具</span><nav aria-label="辅助导航">{[['task','browser','任务调试'],['history','history','执行历史']].map(([id,icon,name])=><button key={id} className={tab===id?'selected':''} aria-current={tab===id?'page':undefined} aria-label={name} onClick={()=>setTab(id)}><Icon name={icon as IconName}/>{name}</button>)}</nav>
      <div className="sideStatus"><small><Icon name="plug" size={14}/>本机网关</small><p><i className={local.state==='running'?'dot ok':'dot'}/>服务状态 <b>{stateNames[local.state]??local.state}</b></p><p><i className={local.accounts.some(a=>!a.disabled)?'dot ok':'dot'}/>启用账号 <b>{local.accounts.filter(a=>!a.disabled).length}</b></p><p><i className={local.models.length?'dot ok':'dot'}/>可用模型 <b>{local.models.length}</b></p><div className="foot"><Icon name="shield" size={14}/>厂商凭据仅保存在本机</div></div>
    </aside>
    <main><header className="top"><div className="pageIdentity"><Icon name={tab==='models'?'model':tab==='agents'?'plug':tab==='keys'?'shield':tab==='history'?'history':'workspace'} size={17}/><h1>{{a2a:'A2A 接入',gateway:'API 总览',agents:'Agent 接入',keys:'API Keys',task:'任务调试',models:'模型中心',history:'执行历史'}[tab]}</h1><span className="localBadge">token-flowb / local</span></div><div className="topActions">{tab==='task'&&taskMode==='browser'?<><span className="status">{stateNames[control.state]??control.state}</span><button disabled={!!busy||!!active} onClick={newTask}><Icon name="plus" size={15}/>新建任务</button><button disabled={!!busy||!!active} onClick={()=>act('打开浏览器',async()=>{await api('/api/browser/open',{});})}><Icon name="browser" size={16}/>打开任务浏览器 ↗</button></>:<><span className="status"><i className={`dot ${local.state==='running'?'ok':''}`}/>网关{stateNames[local.state]??local.state}</span><button onClick={()=>{setTab('models');setModelView('gateway');}}><Icon name="sliders" size={15}/>网关设置</button></>}</div></header>
      {credentialWarnings.length>0&&<div className="notice credentialWarning" role="alert">{credentialWarnings.map(message=><p key={message}>{message}</p>)}<button onClick={()=>{setTab('models');setModelView('connection');}}>查看模型配置</button><button onClick={()=>setCredentialWarnings([])}>知道了</button></div>}
      {error&&<div className="error" role="alert">{error}<button aria-label="关闭错误" onClick={()=>setError('')}>×</button></div>}
      {notice&&<div className="notice" role="status">{notice}</div>}
      {busy&&<div className="busy" role="status">{busy}…</div>}
      {active&&(tab!=='task'||run?.run.id!==active.run.id)&&<div className="activeTaskBanner" role="status"><span><i className="dot ok"/>有任务正在执行 · {stateNames[control.state]??control.state}</span><button onClick={()=>{setRun(active);setFrame(null);setTab('task');}}>返回当前任务 <Icon name="arrow" size={14}/></button></div>}
      {tab==='a2a'&&<A2APane local={local} onManual={()=>setTab('agents')} onAccounts={()=>{setReturnAfterLogin(local.login?.id??'');setTab('models');setModelView('accounts');}} onMaintenance={()=>{setTaskMode('maintenance');setTab('task');}}/>}
      {tab==='task'&&<div className="modelCenterTabs" role="tablist" aria-label="任务类型"><button role="tab" aria-selected={taskMode==='maintenance'} onClick={()=>setTaskMode('maintenance')}>网关维修</button><button role="tab" aria-selected={taskMode==='browser'} onClick={()=>setTaskMode('browser')}>浏览器任务</button></div>}
      {tab==='task'&&taskMode==='maintenance'&&<MaintenancePane local={local}/>}
      {tab==='gateway'&&<GatewayHome local={local} onNavigate={target=>{if(target==='agents'||target==='keys')setTab(target);else{setTab('models');setModelView(target);}}}/>}
      {tab==='agents'&&<AgentConnections local={local} preferredModel={preferredModel} onKeys={()=>setTab('keys')} onAccounts={()=>{setTab('models');setModelView('accounts');}}/>}
      {tab==='keys'&&<GatewayKeysPane local={local}/>}
      {tab==='task'&&taskMode==='browser'&&<div className={`taskPage ${reviewing?'isReview':''}`}>
        {!run&&<section className="workspaceIntro"><div className="welcomeIdentity"><span className="flowWordmark">token-flowb</span><span>想法 → 行动 → 结果</span></div><h2>让想法，<span>开始流动。</span></h2><p>描述目标，连接你的模型。剩下的步骤，我们一起完成。</p></section>}
        <div className="workspace"><section className="taskRail">
        <div className="composerHeading"><span><Icon name="message" size={16}/>{run?'当前任务':'你想完成什么？'}</span><button className="quietButton" aria-expanded={optionsOpen} aria-controls="task-options" onClick={()=>setOptionsOpen(!optionsOpen)}><Icon name="sliders" size={16}/>浏览器与桌面设置</button></div>
        <form className="taskComposer" onSubmit={e=>{e.preventDefault();if(busy||active||!provider.model||!probe?.functionOutput||(browser.source==='extension'&&!browser.running)||!prompt.trim())return;void act('启动任务',async()=>{const result=await api<{detail:RunDetail}>('/api/runs',{scenarioId:'browser-task',prompt,model:provider.model,maxResponseTurns:turns,browserMode:'headful'});setRun(result.detail);setActive(result.detail);setFrame(null);setOptionsOpen(false);});}}>
          <label className="srOnly" htmlFor="task">{desktop.enabled?'让 Agent 在网页或桌面软件里做什么？':'让 Agent 在当前网页做什么？'}</label><textarea id="task" rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} placeholder={desktop.enabled?'例如：打开「备忘录」，把当前网页的岗位要求整理成一条新备忘。':'例如：阅读当前网页，把关键信息整理成一份清单。你可以描述目标、步骤和希望得到的结果…'} required maxLength={20000}/>
          <div className="composerContext"><span><Icon name="browser" size={14}/>{browser.source==='extension'?'Chrome 当前标签页':'独立任务浏览器'}</span><span>{desktop.enabled?'桌面操作已开启':'仅操作浏览器'}</span></div><div className="formRow"><button type="button" className="modelPicker" onClick={()=>setTab('models')}><Icon name="model" size={17}/><span>{provider.model||'选择模型'}</span><Icon name="chevron" size={12}/></button><button className="primary" disabled={!!busy||!!active||!prompt.trim()||!provider.model||!probe?.functionOutput||(browser.source==='extension'&&!browser.running)}>开始任务 <Icon name="send" size={16}/></button></div>
          {!probe?.functionOutput&&<p className="setupHint">模型尚未就绪，<button type="button" className="textButton" onClick={()=>setTab('models')}>连接模型并检测能力 →</button></p>}
        </form>
        <div className="composerFoot"><span><Icon name="shield" size={13}/>随时暂停，始终由你掌控</span><span>{desktopPlatform==='darwin'?'⌘':'Ctrl'} + Enter 开始任务</span></div>
        {!run&&<div className="taskSuggestions"><div className="sectionTitle"><h2>灵感起点</h2><span>点击填入任务，按需修改</span></div><div className="suggestionGrid">{[
          {icon:'browser',title:'整理网页信息',description:'读懂当前页面，提炼重点',prompt:'请阅读当前打开的网页，整理主要内容、关键信息和需要注意的事项。'},
          {icon:'resume',title:'辅助填写表单',description:'准备填写内容，由你完成提交',prompt:'请检查当前页面的表单，列出需要我提供的信息，获得信息后帮助填写，最终提交由我完成。'},
          {icon:'briefcase',title:'分析岗位要求',description:'梳理职责、要求与匹配要点',prompt:'请阅读当前招聘页面，整理岗位职责、必备技能、加分条件和申请时需要准备的材料。'},
          {icon:'workspace',title:'比较页面内容',description:'对照当前页面中的选项',prompt:'请比较当前页面里的不同选项，按特点、差异和适用场景整理成清晰的对照表。'}
        ].map(item=><button className="suggestion" key={item.title} disabled={!!active} onClick={()=>{setPrompt(item.prompt);document.getElementById('task')?.focus();}}><Icon name={item.icon as IconName} size={21}/><span><strong>{item.title}</strong><small>{item.description}</small></span><Icon name="arrow" size={16}/></button>)}</div></div>}
        <section id="task-options" className="taskOptions" hidden={!optionsOpen}><div className="sectionTitle"><h2>浏览器与桌面设置</h2><button className="iconButton" aria-label="收起任务设置" onClick={()=>setOptionsOpen(false)}><Icon name="close"/></button></div>
        <section className="browserConnection"><label>浏览器来源<select aria-label="浏览器来源" value={browser.source??'dedicated'} disabled={!!busy||!!active} onChange={e=>void act('切换浏览器',async()=>{await api('/api/browser/source',{source:e.target.value});})}><option value="dedicated">Agent 独立浏览器</option><option value="extension">Chrome 当前标签页 · 扩展</option></select></label>
          {browser.source==='extension'&&<><p className="hint">在 chrome://extensions 开启开发者模式，加载随应用提供的 chrome 扩展文件夹。在已登录的网站点击扩展，粘贴连接码后连接。</p><div className="buttons"><button disabled={!!busy||!!active} onClick={()=>void act('生成连接码',async()=>{const result=await api<{connectionURL:string}>('/api/browser/extension/pair',{});setConnection(result.connectionURL);})}>生成连接码</button><button disabled={!!busy} onClick={()=>void act('断开 Chrome',async()=>{await api('/api/browser/extension/disconnect',{});setConnection('');})}>断开连接</button></div>{connection&&!browser.running&&<label>连接码 · 单次使用，5 分钟有效<input readOnly value={connection} onFocus={e=>e.target.select()}/><button onClick={()=>void act('复制连接码',async()=>{await copyText(connection);setNotice('已复制，请在 Chrome 扩展中粘贴。');})}>复制连接码</button></label>}<p className="hint">{browser.running?`已连接：${browser.tabs[0]?.title??''}`:'等待 Chrome 扩展连接'}。仅操作所选标签页，断开不会关闭 Chrome。</p></>}
        </section>
        <section className="desktopControl"><label className="toggle"><input type="checkbox" aria-label="允许操作桌面应用" checked={desktop.enabled} disabled={!!busy||!!active||!desktop.supported} onChange={e=>{const enabled=e.target.checked;setDesktop(d=>({...d,enabled}));void act(enabled?'开启桌面操作':'关闭桌面操作',async()=>{setDesktop(await api('/api/desktop',{enabled}));});}}/><span>允许操作桌面应用 <small>{desktop.platform==='darwin'?'macOS':desktop.platform==='win32'?'Windows':desktop.platform}</small></span></label>
          <p className="hint">{!desktop.supported?'仅支持 Windows 与 macOS。':desktop.enabled?'Agent 可对主显示器截图并操作鼠标键盘、打开应用。任务期间请勿使用键盘鼠标，随时可点「暂停 / 人工接管」。':'关闭时 Agent 只能操作浏览器。开启后每次启动应用都需要重新确认。'}</p>
          {desktop.enabled&&desktop.platform==='darwin'&&<div className="permissions">{([['accessibility','辅助功能 · 鼠标键盘'],['screenRecording','屏幕录制 · 截图']] as const).map(([key,label])=><span key={key}><i className={`dot ${desktop.permissions?.[key]===true?'ok':desktop.permissions?.[key]===false?'bad':''}`}/>{label} <b>{desktop.permissions?.[key]===true?'已授权':desktop.permissions?.[key]===false?'未授权':'未知'}</b></span>)}
            {(desktop.permissions?.accessibility!==true||desktop.permissions?.screenRecording!==true)&&<button disabled={!!busy||!!active} onClick={()=>void act('申请系统权限',async()=>{setDesktop(await api('/api/desktop/permissions',{}));setNotice('如系统弹出授权窗口，请为 token-flowb 开启权限；已在「系统设置 → 隐私与安全性」中授权的可直接刷新。');})}>申请系统权限</button>}</div>}</section>
<label className="turnLimit">最大轮次<input className="number" type="number" min="1" max="50" value={turns} onChange={e=>setTurns(Number(e.target.value))}/><small>限制单次任务的模型调用轮次</small></label></section>

        {active&&<div className="runActions"><button disabled={control.state!=='agent_control'} onClick={()=>act('请求接管',async()=>{setControl(await api('/api/control/pause',{}));})}>暂停 / 人工接管</button><button className="danger" onClick={()=>act('停止任务',async()=>{setRun(await api(`/api/runs/${active.run.id}/stop`,{}));})}>停止任务</button></div>}
        {control.pending&&<section className="approval"><div className="eyebrow">HUMAN TAKEOVER</div><h2>现在由你操作</h2><p>{control.pending.message}</p><p className="hint">{desktop.enabled?'在浏览器或桌面软件中完成操作，再点击继续。':'在 任务浏览器 中完成操作，再点击继续。'}</p><button className="primary" disabled={!!busy} onClick={()=>act('继续',async()=>{await api('/api/control/resume',{id:control.pending!.id});})}>让 Agent 继续</button></section>}
        {run?.run.status==='completed'&&<section className="result"><div className="eyebrow">TASK COMPLETED</div><h2>执行结果</h2><p>{[...run.events].reverse().find(e=>e.message==='Model returned a final response.')?.detail??'任务已完成，可查看执行记录与截图。'}</p></section>}
        {run&&<section className="events"><div className="sectionTitle"><h2>执行记录</h2><span className="mono">{run?.events.length??0} EVENTS</span></div>{run.events.map(event=><details key={event.id}><summary><i className={`dot ${event.level==='ok'?'ok':event.level==='error'?'bad':''}`}/><span>{event.message}</span><time>{new Date(event.createdAt).toLocaleTimeString()}</time></summary>{event.detail&&<pre>{event.detail}</pre>}</details>)}</section>}
      </section>{reviewing&&<section className="preview"><div className="sectionTitle"><h2>浏览器观察</h2><div className="previewActions"><span>{run?stateNames[run.run.status]:'尚无任务'}</span>{!run&&<button className="iconButton" aria-label="收起浏览器观察" onClick={()=>setPreviewOpen(false)}><Icon name="close" size={16}/></button>}</div></div><ScreenshotPane emptyReviewMessage="打开任务浏览器 并登录目标网站。任务截图会保存在本机，可沿时间线回看。" onJumpToLatestScreenshot={()=>setFrame(null)} onOpenReplay={()=>act('导出 Replay',async()=>{const replay=await api(run!.replayUrl);const url=URL.createObjectURL(new Blob([JSON.stringify(replay,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${run!.run.id}.json`;a.click();URL.revokeObjectURL(url);})} onScrubberChange={v=>setFrame(Number(v))} onSelectScreenshot={id=>setFrame(shots.findIndex(s=>s.id===id))} replayDisabled={!run} runnerBaseUrl="" screenshots={shots} selectedBrowser={run?.browser??null} selectedRun={run} selectedScenarioTitle="任务浏览器" selectedScreenshot={shot} selectedScreenshotIndex={index} stageUrl={browser.tabs.at(-1)?.url??'等待打开浏览器'} viewingLiveFrame={frame===null}/>
      <div className="browserTabs"><small>已打开的标签页 · {browser.tabs.length}</small>{!browser.tabs.length&&<p className="hint">打开浏览器后，当前页面会显示在这里。</p>}{browser.tabs.map(t=><div key={t.index}><span className="mono">{String(t.index+1).padStart(2,'0')}</span><span>{t.title||'Untitled'}<small>{t.url}</small></span></div>)}</div></section>}</div>{!reviewing&&<div className="workspaceFoot"><span><Icon name="browser" size={14}/>{browser.running?'浏览器已连接':'使用已有登录状态，任务截图留在本机'}</span><button className="textButton" onClick={()=>setPreviewOpen(true)}>查看浏览器与回放 <Icon name="arrow" size={14}/></button></div>}{!reviewing&&<aside className="environmentRail" aria-label="运行环境">
          <div className="environmentTitle"><h2>运行环境</h2><span className="localPill"><Icon name="shield" size={12}/>本机</span></div>
          <p className="railIntro">模型负责思考，浏览器负责行动。</p>
          <button className="environmentItem" onClick={()=>setTab('models')}><span className="environmentIcon"><Icon name="model" size={19}/></span><span><strong>推理模型</strong><small>{provider.model||'尚未选择模型'}</small></span><i className={`dot ${provider.model&&probe?.functionOutput?'ok':''}`}/></button>
          <button className="environmentItem" onClick={()=>{setOptionsOpen(true);requestAnimationFrame(()=>document.getElementById('task-options')?.scrollIntoView({block:'nearest'}));}}><span className="environmentIcon"><Icon name="browser" size={19}/></span><span><strong>任务浏览器</strong><small>{browser.running?'已连接 · 可以开始':browser.source==='extension'?'等待扩展连接':'开始任务时自动打开'}</small></span><i className={`dot ${browser.running?'ok':''}`}/></button>
          <button className="environmentItem" onClick={()=>setTab('models')}><span className="environmentIcon"><Icon name="plug" size={19}/></span><span><strong>本地账号</strong><small>{local.accounts.length?`${local.accounts.length} 个已保存账号`:'连接订阅或使用自己的 API'}</small></span><Icon name="chevron" size={13}/></button>
          <div className="environmentNote"><Icon name="shield" size={18}/><div><strong>执行过程，由你掌控</strong><p>任务中可随时暂停或接管。截图与执行记录保存在本机。</p></div></div>
          <div className="railHistory"><div className="sectionTitle"><h2>最近记录</h2><button className="textButton" onClick={()=>setTab('history')}>全部 <Icon name="arrow" size={12}/></button></div>{history.length?history.slice(0,3).map(item=><button key={item.id} disabled={!!busy} onClick={()=>openHistory(item.id)}><span>{item.prompt}</span><small>{stateNames[item.status]??item.status}</small></button>):<p>完成第一个任务后，<br/>就可以在这里继续回看。</p>}</div>
        </aside>}</div>}
      {tab==='models'&&<><button className="returnA2A" onClick={()=>setTab('a2a')}>← 返回接入首页</button><div className="modelCenterHeading"><div><span className="eyebrow">YOUR MODELS, ONE PLACE</span><h2>连接一次，模型随时可用。</h2><p>认证厂商账号，查看额度，将可用模型提供给你的 Agent。</p></div><div className="gatewaySummary"><span><i className={`dot ${local.state==='running'?'ok':''}`}/>网关{stateNames[local.state]??local.state}</span><strong>{local.accounts.filter(a=>!a.disabled).length}<small>启用账号</small><b>·</b>{local.models.length}<small>可用模型</small></strong></div></div><div className="modelCenterTabs" role="tablist" aria-label="模型中心">{([['accounts','账号与模型'],['connection','接口与能力'],['keys','API Keys'],['gateway','网关设置']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={modelView===id} onClick={()=>setModelView(id)}>{label}</button>)}<span>{provider.model?`当前模型 · ${provider.model}`:'尚未选择任务模型'}</span></div></>}
      {tab==='models'&&modelView==='connection'&&<div className="settings"><section><div className="sectionTitle"><h2>任务模型</h2><span>选择接口并验证能力</span></div><p className="hint">已连接账号的模型可在「账号与模型」中选择。也可以接入 OpenAI 或其他兼容接口。</p><form onSubmit={e=>{e.preventDefault();void act('保存设置',async()=>{await save();setNotice('设置已保存，请刷新模型并探测能力。');});}}>
        <label>Provider<select value={provider.kind} disabled={!!active} onChange={e=>{const kind=e.target.value as Provider['kind'];setProvider({...provider,kind,baseURL:kind==='openai'?'https://api.openai.com/v1':`http://127.0.0.1:${local.port}/v1`,model:''});setModels([]);setProbe(undefined);}}><option value="cliproxy">本机网关 · 已连接账号</option><option value="openai">OpenAI</option><option value="custom">Custom · OpenAI-compatible</option></select></label>
        <label>Base URL<input required value={provider.baseURL} disabled={provider.kind==='cliproxy'||!!active} onChange={e=>setProvider({...provider,baseURL:e.target.value})}/></label>
        {provider.kind!=='cliproxy'&&<label>API Key <span className="muted">{hasKey?'已保存；留空则保留':''}</span><input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="只写入系统加密存储，不返回明文"/></label>}
        <label>模型 ID<div className="inputAction"><input list="models" required value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})} placeholder="从当前 Provider 获取或输入准确模型 ID"/><button type="button" disabled={!!busy||!!active} onClick={()=>act('读取模型',async()=>{await save();setModels((await api<{data:{id:string}[]}>('/api/providers/models')).data);})}>刷新模型</button></div><datalist id="models">{(provider.kind==='cliproxy'?local.models:models).map(m=><option key={m.id} value={m.id}/>)}</datalist></label>
        <div className="columns"><label>对话历史<select value={provider.historyMode} onChange={e=>setProvider({...provider,historyMode:e.target.value as Provider['historyMode']})}><option value="stateless">无状态 · 发送完整历史</option><option value="previous_response_id">previous_response_id</option></select></label><label>Reasoning<select value={provider.reasoning} onChange={e=>setProvider({...provider,reasoning:e.target.value as Provider['reasoning']})}>{['off','low','medium','high'].map(v=><option key={v}>{v}</option>)}</select></label></div>
        <div className="buttons"><button type="submit" disabled={!!busy||!!active}>保存设置</button><button type="button" className="primary" disabled={!!busy||!!active||!provider.model} onClick={()=>act('探测模型能力（会请求 Provider）',async()=>{await save();setProbe(await api('/api/providers/probe',{}));})}>保存并探测能力 →</button></div>
      </form></section><section><h2>能力探测</h2><p className="hint">实际请求验证，不由模型名称推断。历史续接和图片为独立能力，失败不等于模型整体不可用。探测会产生少量模型调用。</p>{probe?.responses && !probe.previousResponseId && <p className="hint">此链路未通过 previous_response_id。请将「对话历史」改为 stateless（完整历史回传），保存并重新探测后运行。</p>}<div className="probe">{[['responses','Responses API'],['functionCall','Function Call'],['functionOutput','Function Output'],['previousResponseId','previous_response_id'],['imageInput','Image Input'],['reasoning','Reasoning']].map(([key,label])=><div key={key}><span className="mono">{label}</span><b className={probe?.[key as keyof Probe]===true?'good':''}>{!probe?'未探测':probe.errors[key]?.startsWith('未执行：')?'— 未执行':probe[key as keyof Probe]===true?'✓ 通过':'× 未通过'}</b>{probe?.errors[key]&&<small>{probe.errors[key]}</small>}</div>)}</div><div className="connectionNext"><h2>供其他应用调用</h2><p className="hint">所有已连接账号的可用模型统一由本机网关提供。在「API Keys」创建客户端密钥，勾选允许调用的提供商与模型后即可接入。</p><button onClick={()=>setModelView('keys')}>管理客户端 Key →</button></div></section></div>}
      {tab==='models'&&modelView==='keys'&&<GatewayKeysPane local={local}/>}
      {tab==='models'&&(modelView==='accounts'||modelView==='gateway')&&<LocalAgentPane view={modelView} selectedModel={provider.kind==='cliproxy'?provider.model:''} local={local} disabled={!!busy||!!active} onAction={command}
        onGateway={apiKey=>act(apiKey?'保存 API Key':'重新生成 API Key',async()=>{await api('/api/local-agent/gateway',{apiKey:apiKey??''},'PUT');})}
        onLoginAction={(action,data)=>act('处理授权',async()=>{setLocal(await api(`/api/local-agent/login/${action}`,data));})}
        onAccount={(id,enabled)=>act(enabled?'启用账号':'停用账号',async()=>{setLocal(await api(`/api/local-agent/accounts/${id}`,{enabled}));})}
        onDeleteAccount={id=>act('删除账号凭据',async()=>{setLocal(await api(`/api/local-agent/accounts/${id}`,undefined,'DELETE'));setNotice('已成功删除该账号凭据文件。');})}
        onImportLocal={provider=>act('导入本机应用凭据',async()=>{setLocal(await api(`/api/local-agent/import-local/${provider}`,{}));setNotice(`已成功导入本机 ${provider} 账号凭据。`);})}
        onUseModel={async model=>{setPreferredModel(model);setTab('agents');}}/>}
      {tab==='history'&&<section className="history"><div className="sectionTitle"><h2>本机任务记录</h2><span>{visibleHistory.length} / {history.length} 条记录</span></div><div className="historyFilters"><label><span className="srOnly">搜索任务记录</span><input type="search" value={historyQuery} onChange={e=>setHistoryQuery(e.target.value)} placeholder="搜索任务内容或模型…"/></label><label><span className="srOnly">任务状态</span><select aria-label="任务状态" value={historyStatus} onChange={e=>setHistoryStatus(e.target.value)}><option value="all">全部状态</option><option value="completed">已完成</option><option value="failed">失败</option><option value="cancelled">已停止</option><option value="running">运行中</option></select></label></div>{!history.length?<div className="empty"><Icon name="history" size={32}/><h2>还没有任务记录</h2><p>完成第一个任务后，可在这里查看截图与执行过程。</p><button onClick={()=>setTab('task')}>前往工作台 →</button></div>:!visibleHistory.length?<div className="empty"><Icon name="history" size={28}/><h2>没有匹配的任务</h2><p>试试其他关键词，或清除筛选条件。</p><button onClick={()=>{setHistoryQuery('');setHistoryStatus('all');}}>清除筛选</button></div>:visibleHistory.map(item=><button className="historyRow" disabled={!!busy} key={item.id} onClick={()=>openHistory(item.id)}><span className="mono">{new Date(item.startedAt).toLocaleString()}</span><strong>{item.prompt}</strong><span>{item.model}</span><b>{stateNames[item.status]}</b></button>)}</section>}
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
