import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { RunDetail, RunRecord } from '@cua-sample/contracts';
import { ScreenshotPane } from './ScreenshotPane';
import './style.css';
import { LocalAgentPane } from './LocalAgentPane';
import type { LocalAgentSnapshot } from '../../../packages/core/src/cliproxy';

type Provider={kind:'cliproxy'|'openai'|'custom';baseURL:string;model:string;historyMode:'stateless'|'previous_response_id';reasoning:'off'|'low'|'medium'|'high'};
type Control={state:string;pending?:{id:string;kind:'human';message:string}};
type Local=LocalAgentSnapshot;
type Probe={responses:boolean;functionCall:boolean;functionOutput:boolean;previousResponseId:boolean;imageInput:boolean;reasoning:boolean;errors:Record<string,string>};
async function api<T>(path:string,body?:unknown,method?:string):Promise<T>{
  const response=await fetch(path,{method:method??(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await response.json();if(!response.ok)throw new Error(data.error??data.message??`HTTP ${response.status}`);return data;
}
const stateNames:Record<string,string>={idle:'空闲',agent_control:'Agent 正在操作',pausing:'等待当前操作结束',human_control:'人工接管',resync:'同步页面状态',running:'运行中',completed:'已完成',failed:'失败',cancelled:'已停止',stopped:'已停止',starting:'启动中'};
function App(){
  const [tab,setTab]=useState('task'); const [error,setError]=useState('');const [busy,setBusy]=useState('');
  const [provider,setProvider]=useState<Provider>({kind:'cliproxy',baseURL:'http://127.0.0.1:8317/v1',model:'',historyMode:'stateless',reasoning:'off'});
  const [apiKey,setApiKey]=useState('');const [hasKey,setHasKey]=useState(false); const [probe,setProbe]=useState<Probe>();const [models,setModels]=useState<{id:string}[]>([]);
  const [control,setControl]=useState<Control>({state:'idle'});const [local,setLocal]=useState<Local>({state:'stopped',loginState:'idle',port:8317,logs:[],accounts:[],models:[],accountError:undefined,login:undefined});
  const [browser,setBrowser]=useState<{running:boolean;tabs:{index:number;url:string;title:string}[]}>({running:false,tabs:[]});
  const [run,setRun]=useState<RunDetail|null>(null);const [active,setActive]=useState<RunDetail|null>(null);const [history,setHistory]=useState<RunRecord[]>([]);
  const [prompt,setPrompt]=useState('');const [turns,setTurns]=useState(24);const [frame,setFrame]=useState<number|null>(null);const [notice,setNotice]=useState('');
  async function refresh(){const [c,l,b,a,h]=await Promise.all([api<Control>('/api/control'),api<Local>('/api/local-agent'),api<typeof browser>('/api/browser'),api<RunDetail|null>('/api/runs/active'),api<RunRecord[]>('/api/history')]);setControl(c);setLocal(l);setBrowser(b);setActive(a);setHistory(h);if(a)setRun(current=>!current||current.run.id===a.run.id?a:current);}
  const act=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setError('');setNotice('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy('');}};
  useEffect(()=>{void api<{provider:Provider;hasKey:boolean;probe?:Probe}>('/api/settings').then(s=>{setProvider(s.provider);setHasKey(s.hasKey);setProbe(s.probe);}).catch(e=>setError(e.message));void refresh().catch(e=>setError(e.message));const timer=setInterval(()=>void refresh().catch(()=>{}),1500);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!active)return;const stream=new EventSource(active.eventStreamUrl);stream.onmessage=event=>{const data=JSON.parse(event.data);if(['run_completed','run_failed','run_cancelled'].includes(data.type)){setActive(null);setControl({state:'idle'});}void api<RunDetail>(`/api/runs/${active.run.id}`).then(setRun).catch(()=>{});};return()=>stream.close();},[active?.run.id]);
  const shots=run?.browser?.screenshots??[];const index=frame===null?shots.length-1:Math.min(frame,shots.length-1);const shot=shots[index]??null;
  const save=async()=>{await api('/api/settings',{provider,...(apiKey?{apiKey}:{})},'PUT');setApiKey('');setHasKey(provider.kind==='cliproxy'||!!apiKey||hasKey);setProbe(undefined);};
  const command=(action:string)=>act(action,async()=>{setLocal(await api(`/api/local-agent/${action}`,{}));});
  return <div className="app">
    <aside className="sidebar"><div className="brand"><span className="mark">BA</span><div>Browser Agent<small>LOCAL WORKSPACE / 0.1</small></div></div>
      <nav aria-label="主导航">{[['task','01','任务工作台'],['provider','02','模型与接口'],['local','03','Local Agent'],['history','04','执行历史']].map(([id,num,name])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}><span>{num}</span>{name}</button>)}</nav>
      <div className="sideStatus"><small>RUNTIME</small><p><i className={browser.running?'dot ok':'dot'}/>Browser <b>{browser.running?'已打开':'未启动'}</b></p><p><i className={local.state==='running'?'dot ok':'dot'}/>CLIProxy <b>{stateNames[local.state]??local.state}</b></p><div className="foot">独立浏览器身份 · default<br/>登录状态保留在本机</div></div>
    </aside>
    <main><header className="top"><div><span className="eyebrow">DESKTOP BROWSER AGENT</span><h1>{{task:'任务工作台',provider:'模型与接口',local:'Local Agent',history:'执行历史'}[tab]}</h1></div><div className="topActions"><span className="status"><i className={`dot ${control.state==='agent_control'?'ok':''}`}/>{stateNames[control.state]??control.state}</span><button disabled={!!busy} onClick={()=>act('打开浏览器',async()=>{await api('/api/browser/open',{});})}>打开 Agent Browser ↗</button></div></header>
      {error&&<div className="error" role="alert">{error}<button aria-label="关闭错误" onClick={()=>setError('')}>×</button></div>}
      {notice&&<div className="notice" role="status">{notice}</div>}
      {busy&&<div className="busy" role="status">{busy}…</div>}
      {tab==='task'&&<div className="workspace"><section className="taskRail"><div className="sectionTitle"><h2>新的任务</h2><span className="mono">{provider.model||'尚未选择模型'}</span></div>
        <form onSubmit={e=>{e.preventDefault();void act('启动任务',async()=>{const result=await api<{detail:RunDetail}>('/api/runs',{scenarioId:'browser-task',prompt,model:provider.model,maxResponseTurns:turns,browserMode:'headful'});setRun(result.detail);setActive(result.detail);setFrame(null);});}}>
          <label htmlFor="task">让 Agent 在当前网页做什么？</label><textarea id="task" rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="例如：读取当前招聘页面，整理岗位要求；帮我填写表单，最终提交由我完成。" required maxLength={20000}/>
          <div className="formRow"><label>最大轮次 <input className="number" type="number" min="1" max="50" value={turns} onChange={e=>setTurns(Number(e.target.value))}/></label><button className="primary" disabled={!!busy||!!active||!provider.model||!probe?.functionOutput}>开始任务 →</button></div>
          {!probe?.functionOutput&&<p className="hint">先在「模型与接口」保存模型并完成能力探测。</p>}
        </form>
        {active&&<div className="runActions"><button disabled={control.state!=='agent_control'} onClick={()=>act('请求接管',async()=>{setControl(await api('/api/control/pause',{}));})}>暂停 / 人工接管</button><button className="danger" onClick={()=>act('停止任务',async()=>{setRun(await api(`/api/runs/${active.run.id}/stop`,{}));})}>停止任务</button></div>}
        {control.pending&&<section className="approval"><div className="eyebrow">HUMAN TAKEOVER</div><h2>现在由你操作</h2><p>{control.pending.message}</p><p className="hint">在 Agent Browser 中完成操作，再点击继续。</p><button className="primary" disabled={!!busy} onClick={()=>act('继续',async()=>{await api('/api/control/resume',{id:control.pending!.id});})}>让 Agent 继续</button></section>}
        {run?.run.status==='completed'&&<section className="result"><div className="eyebrow">TASK COMPLETED</div><h2>执行结果</h2><p>{[...run.events].reverse().find(e=>e.message==='Model returned a final response.')?.detail??'任务已完成，可查看执行记录与截图。'}</p></section>}
        <section className="events"><div className="sectionTitle"><h2>执行记录</h2><span className="mono">{run?.events.length??0} EVENTS</span></div>{!run?<p className="hint">任务启动后，模型调用、代码执行和截图会按顺序出现在这里。</p>:run.events.map(event=><details key={event.id}><summary><i className={`dot ${event.level==='ok'?'ok':event.level==='error'?'bad':''}`}/><span>{event.message}</span><time>{new Date(event.createdAt).toLocaleTimeString()}</time></summary>{event.detail&&<pre>{event.detail}</pre>}</details>)}</section>
      </section><section className="preview"><div className="sectionTitle"><h2>浏览器观察 / Replay</h2><span>{run?stateNames[run.run.status]:'尚无任务'}</span></div><ScreenshotPane emptyReviewMessage="打开 Agent Browser 并登录目标网站。任务截图会保存在本机，可沿时间线回看。" onJumpToLatestScreenshot={()=>setFrame(null)} onOpenReplay={()=>act('导出 Replay',async()=>{const replay=await api(run!.replayUrl);const url=URL.createObjectURL(new Blob([JSON.stringify(replay,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${run!.run.id}.json`;a.click();URL.revokeObjectURL(url);})} onScrubberChange={v=>setFrame(Number(v))} onSelectScreenshot={id=>setFrame(shots.findIndex(s=>s.id===id))} replayDisabled={!run} runnerBaseUrl="" screenshots={shots} selectedBrowser={run?.browser??null} selectedRun={run} selectedScenarioTitle="Agent Browser" selectedScreenshot={shot} selectedScreenshotIndex={index} stageUrl={browser.tabs.at(-1)?.url??'等待打开浏览器'} viewingLiveFrame={frame===null}/>
      <div className="browserTabs"><small>OPEN TABS</small>{browser.tabs.map(t=><div key={t.index}><span className="mono">{String(t.index+1).padStart(2,'0')}</span><span>{t.title||'Untitled'}<small>{t.url}</small></span></div>)}</div></section></div>}
      {tab==='provider'&&<div className="settings"><section><div className="sectionTitle"><h2>Responses Provider</h2><span>本机接口转换 / 模型能力</span></div><p className="hint">Local Agent 使用受管 CLIProxyAPI。已有本地代理请选 Custom，直接复用其接口。</p><form onSubmit={e=>{e.preventDefault();void act('保存设置',async()=>{await save();setNotice('设置已保存，请刷新模型并探测能力。');});}}>
        <label>Provider<select value={provider.kind} disabled={!!active} onChange={e=>{const kind=e.target.value as Provider['kind'];setProvider({...provider,kind,baseURL:kind==='openai'?'https://api.openai.com/v1':`http://127.0.0.1:${local.port}/v1`,model:''});setModels([]);setProbe(undefined);}}><option value="cliproxy">Local Agent · CLIProxyAPI</option><option value="openai">OpenAI</option><option value="custom">Custom · OpenAI-compatible</option></select></label>
        <label>Base URL<input required value={provider.baseURL} disabled={provider.kind==='cliproxy'||!!active} onChange={e=>setProvider({...provider,baseURL:e.target.value})}/></label>
        {provider.kind!=='cliproxy'&&<label>API Key <span className="muted">{hasKey?'已保存；留空则保留':''}</span><input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="只写入系统加密存储，不返回明文"/></label>}
        <label>模型 ID<div className="inputAction"><input list="models" required value={provider.model} onChange={e=>setProvider({...provider,model:e.target.value})} placeholder="从当前 Provider 获取或输入准确模型 ID"/><button type="button" disabled={!!busy||!!active} onClick={()=>act('读取模型',async()=>{await save();setModels((await api<{data:{id:string}[]}>('/api/providers/models')).data);})}>刷新模型</button></div><datalist id="models">{models.map(m=><option key={m.id} value={m.id}/>)}</datalist></label>
        <div className="columns"><label>对话历史<select value={provider.historyMode} onChange={e=>setProvider({...provider,historyMode:e.target.value as Provider['historyMode']})}><option value="stateless">无状态 · 发送完整历史</option><option value="previous_response_id">previous_response_id</option></select></label><label>Reasoning<select value={provider.reasoning} onChange={e=>setProvider({...provider,reasoning:e.target.value as Provider['reasoning']})}>{['off','low','medium','high'].map(v=><option key={v}>{v}</option>)}</select></label></div>
        <div className="buttons"><button type="submit" disabled={!!busy||!!active}>保存设置</button><button type="button" className="primary" disabled={!!busy||!!active||!provider.model} onClick={()=>act('探测模型能力（会请求 Provider）',async()=>{await save();setProbe(await api('/api/providers/probe',{}));})}>保存并探测能力 →</button></div>
      </form></section><section><h2>能力探测</h2><p className="hint">实际请求验证，不由模型名称推断。历史续接和图片为独立能力，失败不等于模型整体不可用。探测会产生少量模型调用。</p>{probe?.responses && !probe.previousResponseId && <p className="hint">此链路未通过 previous_response_id。请将「对话历史」改为 stateless（完整历史回传），保存并重新探测后运行。</p>}<div className="probe">{[['responses','Responses API'],['functionCall','Function Call'],['functionOutput','Function Output'],['previousResponseId','previous_response_id'],['imageInput','Image Input'],['reasoning','Reasoning']].map(([key,label])=><div key={key}><span className="mono">{label}</span><b className={probe?.[key as keyof Probe]===true?'good':''}>{!probe?'未探测':probe.errors[key]?.startsWith('未执行：')?'— 未执行':probe[key as keyof Probe]===true?'✓ 通过':'× 未通过'}</b>{probe?.errors[key]&&<small>{probe.errors[key]}</small>}</div>)}</div><h2>Local API</h2><p className="hint">启动独立服务 <code>npm run serve</code> 后，可供本机 AI 客户端调用。Bearer Token 保存在服务数据目录的 api-token 文件。</p><pre>GET  /v1/models{'\n'}POST /v1/responses{'\n'}POST /v1/chat/completions</pre><p className="hint">协议转换由 CLIProxyAPI 负责；Browser Agent 提供统一鉴权与浏览器任务 API。</p></section></div>}
      {tab==='local'&&<LocalAgentPane local={local} disabled={!!busy||!!active} onAction={command}
        onLoginAction={(action,data)=>act('处理授权',async()=>{setLocal(await api(`/api/local-agent/login/${action}`,data));})}
        onAccount={(id,enabled)=>act(enabled?'启用账号':'停用账号',async()=>{setLocal(await api(`/api/local-agent/accounts/${id}`,{enabled}));})}
        onUseModel={model=>act('选择 Local Agent 模型',async()=>{
          const selected:Provider={kind:'cliproxy',baseURL:`http://127.0.0.1:${local.port}/v1`,model,historyMode:'stateless',reasoning:'off'};
          await api('/api/settings',{provider:selected},'PUT');setProvider(selected);setModels(local.models);setProbe(undefined);setTab('provider');setNotice('模型已选择，请点击「保存并探测能力」验证实际调用。');
        })}/>}
      {tab==='history'&&<section className="history"><div className="sectionTitle"><h2>本机任务记录</h2><span>{history.length} RUNS</span></div>{!history.length?<div className="empty"><h2>还没有任务记录</h2><p>完成第一个任务后，可在这里查看截图与执行过程。</p><button onClick={()=>setTab('task')}>前往工作台 →</button></div>:history.map(item=><button className="historyRow" key={item.id} onClick={()=>act('读取历史',async()=>{setRun(await api(`/api/runs/${item.id}`));setFrame(null);setTab('task');})}><span className="mono">{new Date(item.startedAt).toLocaleString()}</span><strong>{item.prompt}</strong><span>{item.model}</span><b>{stateNames[item.status]}</b></button>)}</section>}
    </main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
